SELECT COUNT(*) AS cnt_numeric_comma_text
FROM S01_HOSCDA.HOSCDA_ALLPHI.HLTH_OS_CDA_OBSRVTN_VAL_CD_RFRNC
WHERE OBSRVTN_DSPLY_TXT IS NOT NULL
  -- must contain comma
  AND POSITION(',' IN TO_VARCHAR(OBSRVTN_DSPLY_TXT)) > 0

  -- part before comma must be ONLY digits (after trimming spaces)
  AND TRANSLATE(
        TRIM(SPLIT_PART(TO_VARCHAR(OBSRVTN_DSPLY_TXT), ',', 1)),
        '0123456789',''
      ) = ''

  -- part after comma must contain at least one letter (A-Z)
  AND UPPER(SPLIT_PART(TO_VARCHAR(OBSRVTN_DSPLY_TXT), ',', 2)) <> 
      TRANSLATE(UPPER(SPLIT_PART(TO_VARCHAR(OBSRVTN_DSPLY_TXT), ',', 2)),
                'ABCDEFGHIJKLMNOPQRSTUVWXYZ','');


SELECT OBSRVTN_DSPLY_TXT
FROM S01_HOSCDA.HOSCDA_ALLPHI.HLTH_OS_CDA_OBSRVTN_VAL_CD_RFRNC
WHERE OBSRVTN_DSPLY_TXT IS NOT NULL
  AND POSITION(',' IN TO_VARCHAR(OBSRVTN_DSPLY_TXT)) > 0
  AND TRANSLATE(TRIM(SPLIT_PART(TO_VARCHAR(OBSRVTN_DSPLY_TXT), ',', 1)),
                '0123456789','') = ''
  AND UPPER(SPLIT_PART(TO_VARCHAR(OBSRVTN_DSPLY_TXT), ',', 2)) <>
      TRANSLATE(UPPER(SPLIT_PART(TO_VARCHAR(OBSRVTN_DSPLY_TXT), ',', 2)),
                'ABCDEFGHIJKLMNOPQRSTUVWXYZ','')
LIMIT 50;


SELECT
  COUNT_IF(POSITION(',' IN TO_VARCHAR(OBSRVTN_DSPLY_TXT)) > 0) AS normal_comma_cnt,
  COUNT_IF(POSITION('，' IN TO_VARCHAR(OBSRVTN_DSPLY_TXT)) > 0) AS fullwidth_comma_cnt
FROM S01_HOSCDA.HOSCDA_ALLPHI.HLTH_OS_CDA_OBSRVTN_VAL_CD_RFRNC;
