SELECT COUNT(*) AS cnt
FROM S01_HOSCDA.HOSCDA_ALLPHI.HLTH_OS_CDA_OBSRVTN_VAL_CD_RFRNC
WHERE OBSRVTN_DSPLY_TXT IS NOT NULL
  AND POSITION(',' IN TO_VARCHAR(OBSRVTN_DSPLY_TXT)) > 0
  AND TRANSLATE(TO_VARCHAR(OBSRVTN_DSPLY_TXT), '0123456789', '') <> TO_VARCHAR(OBSRVTN_DSPLY_TXT);



SELECT COUNT(*) AS cnt
FROM S01_HOSCDA.HOSCDA_ALLPHI.HLTH_OS_CDA_OBSRVTN_VAL_CD_RFRNC
WHERE OBSRVTN_DSPLY_TXT IS NOT NULL
  AND POSITION(',' IN TO_VARCHAR(OBSRVTN_DSPLY_TXT)) > 1
  AND TRANSLATE(LEFT(TO_VARCHAR(OBSRVTN_DSPLY_TXT), POSITION(',' IN TO_VARCHAR(OBSRVTN_DSPLY_TXT)) - 1),
                '0123456789', '') = '';


SELECT COUNT(*) AS cnt
FROM S01_HOSCDA.HOSCDA_ALLPHI.HLTH_OS_CDA_OBSRVTN_VAL_CD_RFRNC
WHERE OBSRVTN_DSPLY_TXT IS NOT NULL
  AND (POSITION(','  IN TO_VARCHAR(OBSRVTN_DSPLY_TXT)) > 0
    OR POSITION('，' IN TO_VARCHAR(OBSRVTN_DSPLY_TXT)) > 0)
  AND TRANSLATE(TO_VARCHAR(OBSRVTN_DSPLY_TXT), '0123456789', '') <> TO_VARCHAR(OBSRVTN_DSPLY_TXT);


SELECT
  COUNT_IF(POSITION(','  IN TO_VARCHAR(OBSRVTN_DSPLY_TXT)) > 0) AS normal_comma,
  COUNT_IF(POSITION('，' IN TO_VARCHAR(OBSRVTN_DSPLY_TXT)) > 0) AS fullwidth_comma
FROM S01_HOSCDA.HOSCDA_ALLPHI.HLTH_OS_CDA_OBSRVTN_VAL_CD_RFRNC;