
WITH CDA AS (
    SELECT
        OBSR.SRC_ENCNTR_ID,
        PAT.MCID,
        OBSR.OBSRVTN_VAL_TXT AS CDA_VAL_TXT,
        OBSR.CODE AS CDA_CODE
    FROM P01_CDA.CDA_ALLPHI.OBSRVTN OBSR
    INNER JOIN P01_CDA.CDA_ALLPHI.PAT PAT
        ON PAT.PAT_GUID = OBSR.PAT_GUID
    WHERE OBSR.encntr_id_val_txt = '91172951120'
)

, HOSCDA AS (
    SELECT
        ENCNTR_ID_VAL_TXT AS SRC_ENCNTR_ID,
        PAT.MCID,
        OBSR.OBSRVTN_VAL_TXT AS HOSCDA_VAL_TXT,
        VAL_CD.OBSRVTN_DSPLY_TXT,
        VAL_CD.ORGLN_TXT,
        VAL_CD.CD_TRNSLTNG_ID AS HOSCDA_CODE
    FROM HOSCDA_STG.HLTH_OS_CDA_OBSRVTN_STG OBSR
    INNER JOIN HOSCDA_STG.HLTH_OS_CDA_OBSRVTN_CD_RFRNC_STG VAL_CD
        ON OBSR.OBSRVTN_ID = VAL_CD.RSRC_ID
        AND OBSR.EDL_RUN_ID = VAL_CD.EDL_RUN_ID
    INNER JOIN HOSCDA_EXTRACT.PAT_ANTHM_ID PAT
        ON SPLIT_PART(OBSR.SUBJ_RFRNC_TXT,'^',2) = PAT.PAT_GUID
    WHERE OBSR.obsrvtn_val_type_nm = 'CD'
      AND ENCNTR_ID_VAL_TXT = '91172951120'
)
SELECT
    C.SRC_ENCNTR_ID,
    C.MCID,

    C.CDA_VAL_TXT,
    H.HOSCDA_VAL_TXT,

    C.CDA_CODE,
    H.HOSCDA_CODE,

    H.OBSRVTN_DSPLY_TXT,
    H.ORGLN_TXT
FROM CDA C
LEFT JOIN HOSCDA H
    ON C.SRC_ENCNTR_ID = H.SRC_ENCNTR_ID
   AND C.MCID = H.MCID
   AND C.CDA_CODE = H.HOSCDA_CODE;




